### ISSUE TITLE
Latest version broke on react-native apps

### ISSUE THREAD

**Issue by sayem314** [LionRoar/youtube-api-v3-search#3]
Hey there I was on version 1.1.3 and it was working super smooth. Recently after upgrading to the latest version, the functionality of my app has broken so I had to revert back to v1.1.3. Please consider using pure JS component in this project. Here are error logs attached below. Btw this project is awesome.

`Failed building JavaScript bundle.`
`[18:57:00] The package at "node_modules/youtube-api-v3-search/src/request/node-request.js" attempted to import the Node standard library module "https". It failed because React Native does not include the Node standard library.`

**Comment by LionRoar** [comment]
Thank you very much! 
Hopefully, this has been fixed in version 1.2.1 
please feel free to open a new issue at any time waiting for your confirmation on this fix if possible.
thank you! 
have a good one :)

**Comment by sayem314** [comment]
Hey there, It's not working. Here is the new error logs:

`[18:26:56] Failed building JavaScript bundle.
[18:27:06] The package at "node_modules/youtube-api-v3-search/src/common.js" attempted to import the Node standard library module "querystring". It failed because React Native does not include the Node standard library. Read more at https://docs.expo.io/versions/latest/introduction/faq.html#can-i-use-nodejs-packages-with-expo`

**Comment by LionRoar** [comment]
Hi @sayem314  thank you for the feedback I've released a *beta* version as a fix if you confirm the fix I'm going to patch it please install it with 
`$ npm install youtube-api-v3-search@beta`
I'm waiting for your response
have a good day :)

**Comment by sayem314** [comment]
_Hey there, sorry for taking such a long time to reply :disappointed:_

Yes, beta tag seems to be working fine. :yellow_heart:

**Comment by sayem314** [comment]
@LionRoar will you merge beta with latest tag soon? Also error catch doesn’t work very well. App crashes whenever errors occur with api.
