### ISSUE TITLE
Get error

### ISSUE THREAD

**Issue by blackblue2712** [LionRoar/youtube-api-v3-search#5]
i provide my youtube_key and get error

`
errors: [
    {
      domain: 'usageLimits',
      reason: 'keyInvalid',
      message: 'Bad Request'
    }
  ],
  code: 400,
  message: 'Bad Request'
`

**Comment by Rajdeepc** [comment]
Use it like below. It works fine
```
const getYoutubeData = (searchQuery) => {
    const options = {
        q:searchQuery,
        part:'snippet',
        type:'video'
      }
    const YOUTUBE_KEY = <YOUR_KEY>';
    return searchYoutube(YOUTUBE_KEY,options)
    .then(response => {
        return response.data
    })
}
```

**Comment by LionRoar** [comment]
it's a Google API error invalid key because of usage limit reach
